spring.application.name=bytebank

spring.datasource.url=jdbc:postgresql://localhost/bytebank_db
spring.datasource.jdbcUrl=jdbc:postgresql://localhost/bytebank_db
spring.datasource.username=${DB_USER_POSTGRES}
spring.datasource.password=${DB_PASSWORD_POSTGRES}

spring.batch.jdbc.initialize-schema=always

spring.jpa.hibernate.ddl-auto=update